# Generated by Django 5.1.6 on 2025-02-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakila_db', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
